export enum TipoDrawer {
  INSTANCE = 'INSTANCE',
  REABRIR_PROTOCOLO = 'REABRIR_PROTOCOLO',
  VISUALIZAR_ARQUIVOS = 'VISUALIZAR_ARQUIVOS',
  COMENTARIOS = 'COMENTARIOS',
  DETALHES_TAREFA = 'DETALHES_TAREFA'
}
