export enum Role {
  ESSA = 'ESSA',
  DEPARTMENT = 'DEPARTMENT',
  ADM = 'ADM',
  AUS = 'AUS',
  EUS = 'EUS',
  RUS = 'RUS',
  CUS = 'CUS',
  HIS = 'HIS',
  BATCH_READ = 'BATCH_READ',
  BATCH_DELETE = 'BATCH_DELETE',
  BATCH_CREATE = 'BATCH_CREATE',
  DECISIION_DEFINITIO_READ = 'DECISIION_DEFINITIO_READ',
  DECISIION_DEFINITIO_DELETE = 'DECISIION_DEFINITIO_DELETE',
  DECISIION_DEFINITIO_CREATE = 'DECISIION_DEFINITIO_CREATE',
  DECISIION_REQUERIMENTS_READ = 'DECISIION_REQUERIMENTS_READ',
  DEPLOY_READ = 'DEPLOY_READ',
  DEPLOY_DELETE = 'DEPLOY_DELETE',
  DEPLOY_CREATE = 'DEPLOY_CREATE',
  FILTER_READ = 'FILTER_READ',
  FILTER_DELETE = 'FILTER_DELETE',
  FILTER_CREATE = 'FILTER_CREATE',
  MESSAGE_SIGNAL = 'MESSAGE_SIGNAL',
  GROUP_READ = 'GROUP_READ',
  GROUP_DELETE = 'GROUP_DELETE',
  GROUP_CREATE = 'GROUP_CREATE',
  HISTORIC_PROCESS_READ = 'HISTORIC_PROCESS_READ',
  HISTORIC_TASK_READ = 'HISTORIC_TASK_READ',
  LOG_READ = 'LOG_READ',
  LOG_DELETE = 'LOG_DELETE',
  PROCESS_DEFINITION_READ = 'PROCESS_DEFINITION_READ',
  PROCESS_DEFINITION_DELETE = 'PROCESS_DEFINITION_DELETE',
  UPDATE_INSTANCE_VARIABLE = 'UPDATE_INSTANCE_VARIABLE',
  PROCESS_DEFINITION_CREATE = 'PROCESS_DEFINITION_CREATE',
  PROCESS_INSTANCE_READ = 'PROCESS_INSTANCE_READ',
  PROCESS_INSTANCE_DELETE = 'PROCESS_INSTANCE_DELETE',
  PROCESS_INSTANCE_CREATE = 'PROCESS_INSTANCE_CREATE',
  TASK_ASSIGN = 'TASK_ASSIGN',
  TASK_READ = 'TASK_READ',
  TASK_DELETE = 'TASK_DELETE',
  TASK_CREATE = 'TASK_CREATE'
}

export const RoleDescriptions: Record<Role, string> = {
  [Role.ESSA]: 'Grupos de autorização camunda',
  [Role.DEPARTMENT]: 'Grupos de departamentos',
  [Role.ADM]: 'Administrador',
  [Role.AUS]: 'Administrar usuários',
  [Role.EUS]: 'Editar usuários',
  [Role.RUS]: 'Remover usuários',
  [Role.CUS]: 'Cria usuários',
  [Role.HIS]: 'Ver histórico',
  [Role.BATCH_READ]: 'Ler lotes',
  [Role.BATCH_DELETE]: 'Remover lotes',
  [Role.BATCH_CREATE]: 'Criar atualizar lotes',
  [Role.DECISIION_DEFINITIO_READ]: 'Ver decisões',
  [Role.DECISIION_DEFINITIO_DELETE]: 'Remover decisões',
  [Role.DECISIION_DEFINITIO_CREATE]: 'Criar atualizar decisões',
  [Role.DECISIION_REQUERIMENTS_READ]: 'Ler requerimentos de decisões',
  [Role.DEPLOY_READ]: 'Ver implantações',
  [Role.DEPLOY_DELETE]: 'Remover implantações',
  [Role.DEPLOY_CREATE]: 'Criar atualizar implantações',
  [Role.FILTER_READ]: 'Ver filtros',
  [Role.FILTER_DELETE]: 'Remover filtros',
  [Role.FILTER_CREATE]: 'Criar atualizar filtros',
  [Role.MESSAGE_SIGNAL]: 'Enviar mensagem signal',
  [Role.GROUP_READ]: 'Ver departamentos',
  [Role.GROUP_DELETE]: 'Remover departamentos',
  [Role.GROUP_CREATE]: 'Criar atualizar departamentos',
  [Role.HISTORIC_PROCESS_READ]: 'Ver históricos de processos',
  [Role.HISTORIC_TASK_READ]: 'Ver históricos de tarefas',
  [Role.LOG_READ]: 'Ver logs',
  [Role.LOG_DELETE]: 'Remover logs',
  [Role.PROCESS_DEFINITION_READ]: 'Ver definições de processos',
  [Role.PROCESS_DEFINITION_DELETE]: 'Remover definições de processos',
  [Role.UPDATE_INSTANCE_VARIABLE]: 'Atualizar variaveis da instância',
  [Role.PROCESS_DEFINITION_CREATE]: 'Criar atualizar definições de processos',
  [Role.PROCESS_INSTANCE_READ]: 'Ver instancias de processos',
  [Role.PROCESS_INSTANCE_DELETE]: 'Remover instancias de processos',
  [Role.PROCESS_INSTANCE_CREATE]: 'Criar atualizar instancias de processos',
  [Role.TASK_ASSIGN]: 'Assumir tarefas',
  [Role.TASK_READ]: 'Vere tarefas',
  [Role.TASK_DELETE]: 'Remover tarefas',
  [Role.TASK_CREATE]: 'Criar atualizar tarefas',
};