export enum StatusTarefa {
  ABORT = 'ABORT',
  ACTION = 'ACTION',
  ADD = 'ADD',
  ADD_FILTER_HINT = 'ADD_FILTER_HINT',
  ADD_GROUPS = 'ADD_GROUPS',
  ADD_GROUP_FAILED = 'ADD_GROUP_FAILED',
  ADD_PERMISSION = 'ADD_PERMISSION',
  ADD_SORT_BY = 'ADD_SORT_BY',
  ADD_VARIABLE = 'ADD_VARIABLE',
  ADMIN_APP = 'ADMIN_APP',
  AFTER = 'AFTER',
  ALL_TASKS = 'ALL_TASKS',
  APP_VENDOR = 'APP_VENDOR',
  ASC = 'ASC',
  ASSIGNED_ERROR = 'ASSIGNED_ERROR',
  ASSIGNED_OK = 'ASSIGNED_OK',
  ASSIGNED_TO_YOU = 'ASSIGNED_TO_YOU',
  ASSIGNEE = 'ASSIGNEE',
  ASSIGNEE_RESET_ERROR = 'ASSIGNEE_RESET_ERROR',
  ASSIGNEE_RESET_OK = 'ASSIGNEE_RESET_OK',
  ASSIGN_NOTE_CASE = 'ASSIGN_NOTE_CASE',
  ASSIGN_NOTE_PROCESS = 'ASSIGN_NOTE_PROCESS',
  AUTH_AUTHENTICATION_FAILED = 'AUTH_AUTHENTICATION_FAILED',
  AUTH_DAY_CONTEXT_AFTERNOON = 'AUTH_DAY_CONTEXT_AFTERNOON',
  AUTH_DAY_CONTEXT_DAY = 'AUTH_DAY_CONTEXT_DAY',
  AUTH_DAY_CONTEXT_EVENING = 'AUTH_DAY_CONTEXT_EVENING',
  AUTH_DAY_CONTEXT_MORNING = 'AUTH_DAY_CONTEXT_MORNING',
  AUTH_DAY_CONTEXT_NIGHT = 'AUTH_DAY_CONTEXT_NIGHT',
  AUTH_DAY_CONTEXT_WEEKEND = 'AUTH_DAY_CONTEXT_WEEKEND',
  AUTH_FAILED_TO_DISPLAY_RESOURCE = 'AUTH_FAILED_TO_DISPLAY_RESOURCE',
  AUTH_LOGOUT_SUCCESSFUL = 'AUTH_LOGOUT_SUCCESSFUL',
  AUTH_LOGOUT_THANKS = 'AUTH_LOGOUT_THANKS',
  Activate = 'Activate',
  AddAttachment = 'AddAttachment',
  AddGroupLink = 'AddGroupLink',
  AddUserLink = 'AddUserLink',
  Assign = 'Assign',
  BACK = 'BACK',
  BANNER_CE_EOL_TEXT = 'BANNER_CE_EOL_TEXT',
  BEFORE = 'BEFORE',
  BOOLEAN = 'BOOLEAN',
  BUSINESS_KEY = 'BUSINESS_KEY',
  CANCEL = 'CANCEL',
  CANDIDATE_GROUP = 'CANDIDATE_GROUP',
  CANDIDATE_USER = 'CANDIDATE_USER',
  CAM_WIDGET_BPMN_VIEWER_ERROR = 'CAM_WIDGET_BPMN_VIEWER_ERROR',
  CAM_WIDGET_BPMN_VIEWER_LOADING = 'CAM_WIDGET_BPMN_VIEWER_LOADING',
  CAM_WIDGET_CMMN_VIEWER_ERROR = 'CAM_WIDGET_CMMN_VIEWER_ERROR',
  CAM_WIDGET_CMMN_VIEWER_LOADING = 'CAM_WIDGET_CMMN_VIEWER_LOADING',
  CAM_WIDGET_COPY = 'CAM_WIDGET_COPY',
  CAM_WIDGET_COPY_LINK = 'CAM_WIDGET_COPY_LINK',
  CAM_WIDGET_DMN_VIEWER_ERROR = 'CAM_WIDGET_DMN_VIEWER_ERROR',
  CAM_WIDGET_DMN_VIEWER_LOADING = 'CAM_WIDGET_DMN_VIEWER_LOADING',
  CAM_WIDGET_FOOTER_POWERED_BY = 'CAM_WIDGET_FOOTER_POWERED_BY',
  CAM_WIDGET_FOOTER_TIMEZONE = 'CAM_WIDGET_FOOTER_TIMEZONE',
  CAM_WIDGET_HEADER_MY_PROFILE = 'CAM_WIDGET_HEADER_MY_PROFILE',
  CAM_WIDGET_HEADER_SIGN_OUT = 'CAM_WIDGET_HEADER_SIGN_OUT',
  CAM_WIDGET_HEADER_SMALL_SCREEN_WARNING = 'CAM_WIDGET_HEADER_SMALL_SCREEN_WARNING',
  CAM_WIDGET_HEADER_TOGGLE_NAVIGATION = 'CAM_WIDGET_HEADER_TOGGLE_NAVIGATION',
  CAM_WIDGET_INLINE_FIELD_CRIT_VALUE = 'CAM_WIDGET_INLINE_FIELD_CRIT_VALUE',
  CAM_WIDGET_INLINE_FIELD_CRIT_VALUE_BTN_CHANGE = 'CAM_WIDGET_INLINE_FIELD_CRIT_VALUE_BTN_CHANGE',
  CAM_WIDGET_INLINE_FIELD_CRIT_VALUE_BTN_CLOSE = 'CAM_WIDGET_INLINE_FIELD_CRIT_VALUE_BTN_CLOSE',
  CAM_WIDGET_INLINE_FIELD_CRIT_VALUE_CHANGE = 'CAM_WIDGET_INLINE_FIELD_CRIT_VALUE_CHANGE',
  CAM_WIDGET_SEARCH_MATCH_TYPE = 'CAM_WIDGET_SEARCH_MATCH_TYPE',
  CAM_WIDGET_SEARCH_MATCH_TYPE_ALL = 'CAM_WIDGET_SEARCH_MATCH_TYPE_ALL',
  CAM_WIDGET_SEARCH_MATCH_TYPE_ANY = 'CAM_WIDGET_SEARCH_MATCH_TYPE_ANY',
  CAM_WIDGET_SEARCH_TOTAL_NUMBER_RESULTS = 'CAM_WIDGET_SEARCH_TOTAL_NUMBER_RESULTS',
  CAM_WIDGET_SEARCH_VARIABLE_CASE_ATTRIBUTE = 'CAM_WIDGET_SEARCH_VARIABLE_CASE_ATTRIBUTE',
  CAM_WIDGET_SEARCH_VARIABLE_CASE_NAME = 'CAM_WIDGET_SEARCH_VARIABLE_CASE_NAME',
  CAM_WIDGET_SEARCH_VARIABLE_CASE_VALUE = 'CAM_WIDGET_SEARCH_VARIABLE_CASE_VALUE',
  CAM_WIDGET_STRING_DIALOG_LABEL_CLOSE = 'CAM_WIDGET_STRING_DIALOG_LABEL_CLOSE',
  CAM_WIDGET_STRING_DIALOG_LABEL_VALUE = 'CAM_WIDGET_STRING_DIALOG_LABEL_VALUE',
  CAM_WIDGET_STRING_DIALOG_TITLE = 'CAM_WIDGET_STRING_DIALOG_TITLE',
  CAM_WIDGET_VARIABLES_TABLE_ABORT = 'CAM_WIDGET_VARIABLES_TABLE_ABORT',
  CAM_WIDGET_VARIABLES_TABLE_DELETE = 'CAM_WIDGET_VARIABLES_TABLE_DELETE',
  CAM_WIDGET_VARIABLES_TABLE_DELETE_VARIABLE = 'CAM_WIDGET_VARIABLES_TABLE_DELETE_VARIABLE',
  CAM_WIDGET_VARIABLES_TABLE_DIALOGUE = 'CAM_WIDGET_VARIABLES_TABLE_DIALOGUE',
  CAM_WIDGET_VARIABLES_TABLE_EDIT_VARIABLE = 'CAM_WIDGET_VARIABLES_TABLE_EDIT_VARIABLE',
  CAM_WIDGET_VARIABLES_TABLE_NAME = 'CAM_WIDGET_VARIABLES_TABLE_NAME',
  CAM_WIDGET_VARIABLES_TABLE_NULL = 'CAM_WIDGET_VARIABLES_TABLE_NULL',
  CAM_WIDGET_VARIABLES_TABLE_PLACEHOLDER_VALUE = 'CAM_WIDGET_VARIABLES_TABLE_PLACEHOLDER_VALUE',
  CAM_WIDGET_VARIABLES_TABLE_REVERT_VARIABLE = 'CAM_WIDGET_VARIABLES_TABLE_REVERT_VARIABLE',
  CAM_WIDGET_VARIABLES_TABLE_SAVE_VARIABLE = 'CAM_WIDGET_VARIABLES_TABLE_SAVE_VARIABLE',
  CAM_WIDGET_VARIABLES_TABLE_TOOLTIP_DEFAULT_VALUE = 'CAM_WIDGET_VARIABLES_TABLE_TOOLTIP_DEFAULT_VALUE',
  CAM_WIDGET_VARIABLES_TABLE_TOOLTIP_SET_NULL = 'CAM_WIDGET_VARIABLES_TABLE_TOOLTIP_SET_NULL',
  CAM_WIDGET_VARIABLES_TABLE_TOOLTIP_UPLOAD = 'CAM_WIDGET_VARIABLES_TABLE_TOOLTIP_UPLOAD',
  CAM_WIDGET_VARIABLES_TABLE_TYPE = 'CAM_WIDGET_VARIABLES_TABLE_TYPE',
  CAM_WIDGET_VARIABLES_TABLE_VALUE = 'CAM_WIDGET_VARIABLES_TABLE_VALUE',
  CAM_WIDGET_VARIABLE_DIALOG_BTN_CHANGE = 'CAM_WIDGET_VARIABLE_DIALOG_BTN_CHANGE',
  CAM_WIDGET_VARIABLE_DIALOG_BTN_CLOSE = 'CAM_WIDGET_VARIABLE_DIALOG_BTN_CLOSE',
  CAM_WIDGET_VARIABLE_DIALOG_INSPECT = 'CAM_WIDGET_VARIABLE_DIALOG_INSPECT',
  CAM_WIDGET_VARIABLE_DIALOG_LABEL_OBJECT_TYPE = 'CAM_WIDGET_VARIABLE_DIALOG_LABEL_OBJECT_TYPE',
  CAM_WIDGET_VARIABLE_DIALOG_LABEL_SERIALIZATION = 'CAM_WIDGET_VARIABLE_DIALOG_LABEL_SERIALIZATION',
  CAM_WIDGET_VARIABLE_DIALOG_LABEL_SERIALIZED_VALUE = 'CAM_WIDGET_VARIABLE_DIALOG_LABEL_SERIALIZED_VALUE',
  CAM_WIDGET_VARIABLE_NULL = 'CAM_WIDGET_VARIABLE_NULL',
  CAM_WIDGET_VARIABLE_RESET = 'CAM_WIDGET_VARIABLE_RESET',
  CAM_WIDGET_VARIABLE_SET_VALUE_NULL = 'CAM_WIDGET_VARIABLE_SET_VALUE_NULL',
  CAM_WIDGET_VARIABLE_UNDEFINED = 'CAM_WIDGET_VARIABLE_UNDEFINED',
  CAM_WIDGET_VARIABLE_VALUE = 'CAM_WIDGET_VARIABLE_VALUE',
  CASE_DEFINITION_ID = 'CASE_DEFINITION_ID',
  CASE_DEFINITION_KEY = 'CASE_DEFINITION_KEY',
  CASE_DEFINITION_NAME = 'CASE_DEFINITION_NAME',
  CASE_EXECUTION_ID = 'CASE_EXECUTION_ID',
  CASE_EXECUTION_VARIABLE = 'CASE_EXECUTION_VARIABLE',
  CASE_INSTANCE_BUSINESS_KEY = 'CASE_INSTANCE_BUSINESS_KEY',
  CASE_INSTANCE_ID = 'CASE_INSTANCE_ID',
  CASE_INSTANCE_VARIABLE = 'CASE_INSTANCE_VARIABLE',
  CASE_VARIABLE = 'CASE_VARIABLE',
  CHANGE = 'CHANGE',
  CLAIM_ERROR = 'CLAIM_ERROR',
  CLAIM_OK = 'CLAIM_OK',
  CLAIM_TASK = 'CLAIM_TASK',
  CLICK_PROCESS_TO_START = 'CLICK_PROCESS_TO_START',
  CLOSE = 'CLOSE',
  CLOSE_TASK = 'CLOSE_TASK',
  COCKPIT_APP = 'COCKPIT_APP',
  COMMENT = 'COMMENT',
  COMMENT_CREATE = 'COMMENT_CREATE',
  COMMENT_MESSAGE_PLACEHOLDER = 'COMMENT_MESSAGE_PLACEHOLDER',
  COMMENT_SAVE_ERROR = 'COMMENT_SAVE_ERROR',
  COMPLETE = 'COMPLETE',
  COMPLETE_ERROR = 'COMPLETE_ERROR',
  COMPLETE_OK = 'COMPLETE_OK',
  CREATE_TASK = 'CREATE_TASK',
  CREATION = 'CREATION',
  CREATION_DATE = 'CREATION_DATE',
  CURRENT_GROUPS = 'CURRENT_GROUPS',
  Claim = 'Claim',
  Comment = 'Comment',
  Complete = 'Complete',
  Create = 'Create',
  DATE = 'DATE',
  DELEGATE_ERROR = 'DELEGATE_ERROR',
  DELEGATE_OK = 'DELEGATE_OK',
  DELEGATE_TASK = 'DELEGATE_TASK',
  DELEGATION_STATE = 'DELEGATION_STATE',
  DELETE = 'DELETE',
  DELETE_SEARCH = 'DELETE_SEARCH',
  DESC = 'DESC',
  DESCRIPTION = 'DESCRIPTION',
  DESERIALIZATION_ERROR = 'DESERIALIZATION_ERROR',
  DESERIALIZED = 'DESERIALIZED',
  DIAGRAM = 'DIAGRAM',
  DIAGRAM_RENDER_FAILURE = 'DIAGRAM_RENDER_FAILURE',
  DIRECTIVE_ENGINE_SELECT_MESSAGE_NOT_FOUND = 'DIRECTIVE_ENGINE_SELECT_MESSAGE_NOT_FOUND',
  DIRECTIVE_ENGINE_SELECT_STATUS_NOT_FOUND = 'DIRECTIVE_ENGINE_SELECT_STATUS_NOT_FOUND',
  DIRECTIVE_ENGINE_SELECT_TOOLTIP = 'DIRECTIVE_ENGINE_SELECT_TOOLTIP',
  DIRECTIVE_INPLACE_TEXTFIELD_ERROR_MSG = 'DIRECTIVE_INPLACE_TEXTFIELD_ERROR_MSG',
  DOUBLE = 'DOUBLE',
  DUE = 'DUE',
  DUE_DATE = 'DUE_DATE',
  DUPLICATE_GROUP = 'DUPLICATE_GROUP',
  Delegate = 'Delegate',
  Delete = 'Delete',
  DeleteAttachment = 'DeleteAttachment',
  DeleteGroupLink = 'DeleteGroupLink',
  DeleteUserLink = 'DeleteUserLink',
  EMPTY_CONTEXT_PATH = 'EMPTY_CONTEXT_PATH',
  EMPTY_VALUE = 'EMPTY_VALUE',
  EXECUTION_ID = 'EXECUTION_ID',
  EXECUTION_VARIABLE = 'EXECUTION_VARIABLE',
  EXTERNAL_FORM_LINK = 'EXTERNAL_FORM_LINK',
  FAILED = 'FAILED',
  FAILURE = 'FAILURE',
  FILTER = 'FILTER',
  FILTERS = 'FILTERS',
  FILTERS_LOADING_FAILURE = 'FILTERS_LOADING_FAILURE',
  FILTER_ADD_CRITERION = 'FILTER_ADD_CRITERION',
  FILTER_ADD_VARIABLE = 'FILTER_ADD_VARIABLE',
  FILTER_COLOR_LABEL = 'FILTER_COLOR_LABEL',
  FILTER_CREATE = 'FILTER_CREATE',
  FILTER_CRITERIA_INCLUDE_ASSIGNED_TASKS = 'FILTER_CRITERIA_INCLUDE_ASSIGNED_TASKS',
  FILTER_CRITERIA_INCLUDE_ASSIGNED_TASKS_HINT = 'FILTER_CRITERIA_INCLUDE_ASSIGNED_TASKS_HINT',
  FILTER_CRITERIA_KEY = 'FILTER_CRITERIA_KEY',
  FILTER_CRITERIA_OPERATOR = 'FILTER_CRITERIA_OPERATOR',
  FILTER_CRITERIA_VALUE = 'FILTER_CRITERIA_VALUE',
  FILTER_CRITERION_SUPPORT_EXPRESSION = 'FILTER_CRITERION_SUPPORT_EXPRESSION',
  FILTER_DELETE = 'FILTER_DELETE',
  FILTER_DELETION_ERROR = 'FILTER_DELETION_ERROR',
  FILTER_DELETION_SUCCESS = 'FILTER_DELETION_SUCCESS',
  FILTER_DELETION_WARNING = 'FILTER_DELETION_WARNING',
  FILTER_DESCRIPTION_LABEL = 'FILTER_DESCRIPTION_LABEL',
  FILTER_DESCRIPTION_PLACEHOLDER = 'FILTER_DESCRIPTION_PLACEHOLDER',
  FILTER_DETAILS = 'FILTER_DETAILS',
  FILTER_EDIT = 'FILTER_EDIT',
  FILTER_FORM_BASICS = 'FILTER_FORM_BASICS',
  FILTER_FORM_BASICS_HINT = 'FILTER_FORM_BASICS_HINT',
  FILTER_FORM_CRITERIA = 'FILTER_FORM_CRITERIA',
  FILTER_FORM_CRITERIA_HINT = 'FILTER_FORM_CRITERIA_HINT',
  FILTER_FORM_PERMISSIONS = 'FILTER_FORM_PERMISSIONS',
  FILTER_FORM_PERMISSIONS_DUPLICATE_GROUP = 'FILTER_FORM_PERMISSIONS_DUPLICATE_GROUP',
  FILTER_FORM_PERMISSIONS_DUPLICATE_USER = 'FILTER_FORM_PERMISSIONS_DUPLICATE_USER',
  FILTER_FORM_PERMISSIONS_EDIT_HINT = 'FILTER_FORM_PERMISSIONS_EDIT_HINT',
  FILTER_FORM_PERMISSIONS_GLOBAL = 'FILTER_FORM_PERMISSIONS_GLOBAL',
  FILTER_FORM_PERMISSIONS_GROUP_ID = 'FILTER_FORM_PERMISSIONS_GROUP_ID',
  FILTER_FORM_PERMISSIONS_HINT = 'FILTER_FORM_PERMISSIONS_HINT',
  FILTER_FORM_PERMISSIONS_IDENTITY_TYPE_GROUP = 'FILTER_FORM_PERMISSIONS_IDENTITY_TYPE_GROUP',
  FILTER_FORM_PERMISSIONS_IDENTITY_TYPE_TOOLTIP = 'FILTER_FORM_PERMISSIONS_IDENTITY_TYPE_TOOLTIP',
  FILTER_FORM_PERMISSIONS_IDENTITY_TYPE_USER = 'FILTER_FORM_PERMISSIONS_IDENTITY_TYPE_USER',
  FILTER_FORM_PERMISSIONS_LOADING_FAILURE = 'FILTER_FORM_PERMISSIONS_LOADING_FAILURE',
  FILTER_FORM_PERMISSIONS_REMOVE = 'FILTER_FORM_PERMISSIONS_REMOVE',
  FILTER_FORM_PERMISSIONS_SAVE_ERROR = 'FILTER_FORM_PERMISSIONS_SAVE_ERROR',
  FILTER_FORM_PERMISSIONS_USER_ID = 'FILTER_FORM_PERMISSIONS_USER_ID',
  FILTER_FORM_PERMISSION_GROUP_USER = 'FILTER_FORM_PERMISSION_GROUP_USER',
  FILTER_FORM_PERMISSION_IDENTIFIER = 'FILTER_FORM_PERMISSION_IDENTIFIER',
  FILTER_FORM_VARIABLES = 'FILTER_FORM_VARIABLES',
  FILTER_FORM_VARIABLES_HINT = 'FILTER_FORM_VARIABLES_HINT',
  FILTER_FORM_VARIABLES_SHOW_UNDEFINED = 'FILTER_FORM_VARIABLES_SHOW_UNDEFINED',
  FILTER_NAME_LABEL = 'FILTER_NAME_LABEL',
  FILTER_NAME_PLACEHOLDER = 'FILTER_NAME_PLACEHOLDER',
  FILTER_NOT_FOUND = 'FILTER_NOT_FOUND',
  FILTER_PRIORITY_LABEL = 'FILTER_PRIORITY_LABEL',
  FILTER_REFRESH_LABEL = 'FILTER_REFRESH_LABEL',
  FILTER_REFRESH_TOOLTIP = 'FILTER_REFRESH_TOOLTIP',
  FILTER_REMOVE_CRITERION = 'FILTER_REMOVE_CRITERION',
  FILTER_REMOVE_VARIABLE = 'FILTER_REMOVE_VARIABLE',
  FILTER_SAVE_ERROR = 'FILTER_SAVE_ERROR',
  FILTER_SAVE_SUCCESS = 'FILTER_SAVE_SUCCESS',
  FILTER_VARIABLES_AMOUNT_WARNING = 'FILTER_VARIABLES_AMOUNT_WARNING',
  FILTER_VARIABLE_LABEL = 'FILTER_VARIABLE_LABEL',
  FILTER_VARIABLE_LABEL_PLACEHOLDER = 'FILTER_VARIABLE_LABEL_PLACEHOLDER',
  FILTER_VARIABLE_NAME = 'FILTER_VARIABLE_NAME',
  FILTER_VARIABLE_NAME_PLACEHOLDER = 'FILTER_VARIABLE_NAME_PLACEHOLDER',
  FINISHED = 'FINISHED',
  FIRST_LOGIN_HEADING = 'FIRST_LOGIN_HEADING',
  FIRST_LOGIN_INFO = 'FIRST_LOGIN_INFO',
  FOLLOW_UP = 'FOLLOW_UP',
  FOLLOW_UP_DATE = 'FOLLOW_UP_DATE',
  FORM = 'FORM',
  FORM_FAILURE = 'FORM_FAILURE',
  GROUP = 'GROUP',
  GROUPS = 'GROUPS',
  GROUPS_ADD = 'GROUPS_ADD',
  GROUP_ADD = 'GROUP_ADD',
  GROUP_ADD_ERROR = 'GROUP_ADD_ERROR',
  GROUP_DELETE_ERROR = 'GROUP_DELETE_ERROR',
  GROUP_ID = 'GROUP_ID',
  GROUP_REMOVE = 'GROUP_REMOVE',
  HISTORY = 'HISTORY',
  INIT_EXTERNAL_FORM_FAILED = 'INIT_EXTERNAL_FORM_FAILED',
  INIT_GROUPS_FAILURE = 'INIT_GROUPS_FAILURE',
  INSTANCE_LINK = 'INSTANCE_LINK',
  INSTANCE_SUSPENDED = 'INSTANCE_SUSPENDED',
  INTEGER = 'INTEGER',
  INVALID_DATE = 'INVALID_DATE',
  INVALID_DATE_VALUE = 'INVALID_DATE_VALUE',
  INVALID_SEARCH = 'INVALID_SEARCH',
  INVOLVED_USER = 'INVOLVED_USER',
  LIKE = 'LIKE',
  LOADING = 'LOADING',
  LOAD_VARIABLES = 'LOAD_VARIABLES',
  LOAD_VARIABLES_FAILURE = 'LOAD_VARIABLES_FAILURE',
  LONG = 'LONG',
  MANAGE_ACCOUNT = 'MANAGE_ACCOUNT',
  MANAGE_GROUPS = 'MANAGE_GROUPS',
  MATCH_TYPE = 'MATCH_TYPE',
  MATCH_TYPE_ALL = 'MATCH_TYPE_ALL',
  MATCH_TYPE_ANY = 'MATCH_TYPE_ANY',
  MY_PROFILE = 'MY_PROFILE',
  NAME = 'NAME',
  NEW_TASK_ASSIGNEE = 'NEW_TASK_ASSIGNEE',
  NEW_TASK_DESCRIPTION = 'NEW_TASK_DESCRIPTION',
  NEW_TASK_NAME = 'NEW_TASK_NAME',
  NEW_TASK_TENANT_ID = 'NEW_TASK_TENANT_ID',
  NONE = 'NONE',
  NO_AVAILABLE_FILTER = 'NO_AVAILABLE_FILTER',
  NO_DESCRIPTION = 'NO_DESCRIPTION',
  NO_DIAGRAM = 'NO_DIAGRAM',
  NO_HISTORY = 'NO_HISTORY',
  NO_MATCHING_TASK = 'NO_MATCHING_TASK',
  NO_PROCESS_DEFINITION_AVAILABLE = 'NO_PROCESS_DEFINITION_AVAILABLE',
  NO_TASK_FORM = 'NO_TASK_FORM',
  NO_TASK_VARIABLES = 'NO_TASK_VARIABLES',
  OPERATOR = 'OPERATOR',
  OWNER = 'OWNER',
  OWNER_IS_YOU = 'OWNER_IS_YOU',
  PAGES_MSG_ACCESS_DENIED = 'PAGES_MSG_ACCESS_DENIED',
  PAGES_MSG_ACCESS_DENIED_RESOURCE_ID = 'PAGES_MSG_ACCESS_DENIED_RESOURCE_ID',
  PAGES_MSG_ACTION_DENIED = 'PAGES_MSG_ACTION_DENIED',
  PAGES_MSG_COMMUNICATION_ERROR = 'PAGES_MSG_COMMUNICATION_ERROR',
  PAGES_MSG_ENGINE_NOT_EXISTS = 'PAGES_MSG_ENGINE_NOT_EXISTS',
  PAGES_MSG_NOT_FOUND = 'PAGES_MSG_NOT_FOUND',
  PAGES_MSG_REQUEST_TIMEOUT = 'PAGES_MSG_REQUEST_TIMEOUT',
  PAGES_MSG_SERVER_ERROR = 'PAGES_MSG_SERVER_ERROR',
  PAGES_STATUS_ACCESS_DENIED = 'PAGES_STATUS_ACCESS_DENIED',
  PAGES_STATUS_COMMUNICATION_ERROR = 'PAGES_STATUS_COMMUNICATION_ERROR',
  PAGES_STATUS_NOT_FOUND = 'PAGES_STATUS_NOT_FOUND',
  PAGES_STATUS_REQUEST_TIMEOUT = 'PAGES_STATUS_REQUEST_TIMEOUT',
  PAGES_STATUS_SERVER_ERROR = 'PAGES_STATUS_SERVER_ERROR',
  PAGE_LOGIN_ERROR_MSG = 'PAGE_LOGIN_ERROR_MSG',
  PAGE_LOGIN_FAILED = 'PAGE_LOGIN_FAILED',
  PAGE_LOGIN_PASSWORD = 'PAGE_LOGIN_PASSWORD',
  PAGE_LOGIN_PLEASE_SIGN_IN = 'PAGE_LOGIN_PLEASE_SIGN_IN',
  PAGE_LOGIN_SIGN_IN_ACTION = 'PAGE_LOGIN_SIGN_IN_ACTION',
  PAGE_LOGIN_USERNAME = 'PAGE_LOGIN_USERNAME',
  PAGINATION_FIRST = 'PAGINATION_FIRST',
  PAGINATION_LAST = 'PAGINATION_LAST',
  PAGINATION_NEXT = 'PAGINATION_NEXT',
  PAGINATION_PREVIOUS = 'PAGINATION_PREVIOUS',
  PRIORITY = 'PRIORITY',
  PROCESS_DEFINITION = 'PROCESS_DEFINITION',
  PROCESS_DEFINITION_ID = 'PROCESS_DEFINITION_ID',
  PROCESS_DEFINITION_KEY = 'PROCESS_DEFINITION_KEY',
  PROCESS_DEFINITION_NAME = 'PROCESS_DEFINITION_NAME',
  PROCESS_EXTERNAL_FORM_NOTE = 'PROCESS_EXTERNAL_FORM_NOTE',
  PROCESS_INSTANCE = 'PROCESS_INSTANCE',
  PROCESS_INSTANCE_BUSINESS_KEY = 'PROCESS_INSTANCE_BUSINESS_KEY',
  PROCESS_INSTANCE_ID = 'PROCESS_INSTANCE_ID',
  PROCESS_NAME = 'PROCESS_NAME',
  PROCESS_START_ERROR = 'PROCESS_START_ERROR',
  PROCESS_START_OK = 'PROCESS_START_OK',
  PROCESS_VARIABLE = 'PROCESS_VARIABLE',
  PROPERTY = 'PROPERTY',
  REMOVE = 'REMOVE',
  REMOVE_GROUP_FAILED = 'REMOVE_GROUP_FAILED',
  REMOVE_SORTING = 'REMOVE_SORTING',
  RENDERING = 'RENDERING',
  REQUIRED_FIELD = 'REQUIRED_FIELD',
  REQUIRED_HEX_COLOR_FIELD = 'REQUIRED_HEX_COLOR_FIELD',
  REQUIRED_INTEGER_FIELD = 'REQUIRED_INTEGER_FIELD',
  REQUIRE_UNIQUE_KEY = 'REQUIRE_UNIQUE_KEY',
  REQUIRE_UNIQUE_NAME = 'REQUIRE_UNIQUE_NAME',
  RESET_DUE_DATE = 'RESET_DUE_DATE',
  RESET_FOLLOW_UP_DATE = 'RESET_FOLLOW_UP_DATE',
  RESET_PAGE = 'RESET_PAGE',
  RESET_TASK_ASSIGNEE = 'RESET_TASK_ASSIGNEE',
  RESOLVE_ERROR = 'RESOLVE_ERROR',
  RESOLVE_OK = 'RESOLVE_OK',
  RESTRICTION_NOTICE = 'RESTRICTION_NOTICE',
  SAVE = 'SAVE',
  SAVE_HINT = 'SAVE_HINT',
  SEARCH_BY_TASK_NAME = 'SEARCH_BY_TASK_NAME',
  SEARCH_PLACEHOLDER = 'SEARCH_PLACEHOLDER',
  SEARCH_PROCESS_BY_NAME = 'SEARCH_PROCESS_BY_NAME',
  SEARCH_TASK_BY_NAME = 'SEARCH_TASK_BY_NAME',
  SELECT_TASK_IN_LIST = 'SELECT_TASK_IN_LIST',
  SERIALIZED = 'SERIALIZED',
  SERVICES_RESOURCE_RESOLVER_AUTH_FAILED = 'SERVICES_RESOURCE_RESOLVER_AUTH_FAILED',
  SERVICES_RESOURCE_RESOLVER_DISPLAY_FAILED = 'SERVICES_RESOURCE_RESOLVER_DISPLAY_FAILED',
  SERVICES_RESOURCE_RESOLVER_ID_NOT_FOUND = 'SERVICES_RESOURCE_RESOLVER_ID_NOT_FOUND',
  SERVICES_RESOURCE_RESOLVER_NO_PROMISE = 'SERVICES_RESOURCE_RESOLVER_NO_PROMISE',
  SERVICES_RESOURCE_RESOLVER_RECEIVED_STATUS = 'SERVICES_RESOURCE_RESOLVER_RECEIVED_STATUS',
  SET = 'SET',
  SET_DUE_DATE = 'SET_DUE_DATE',
  SET_FOLLOW_UP_DATE = 'SET_FOLLOW_UP_DATE',
  SHORT = 'SHORT',
  SHORTCUT = 'SHORTCUT',
  SHORTCUT_HELP = 'SHORTCUT_HELP',
  SHOW_LESS = 'SHOW_LESS',
  SHOW_MORE = 'SHOW_MORE',
  SIGN_OUT_ACTION = 'SIGN_OUT_ACTION',
  SORT_BY = 'SORT_BY',
  START = 'START',
  START_PROCESS = 'START_PROCESS',
  STRING = 'STRING',
  SUBMIT = 'SUBMIT',
  SUCCESSFUL = 'SUCCESSFUL',
  SET_OWNER = 'SetOwner',
  SET_PRIORITY = 'SetPriority',
  SUSPEND = 'Suspend',
  TASK = 'TASK',
  TASKLIST_APP = 'TASKLIST_APP',
  TASKS = 'TASKS',
  TASK_DEFINITION_KEY = 'TASK_DEFINITION_KEY',
  TASK_EXTERNAL_FORM_NOTE = 'TASK_EXTERNAL_FORM_NOTE',
  TASK_HAS_BEEN_REMOVED = 'TASK_HAS_BEEN_REMOVED',
  TASK_LIST_LOADING_FAILURE = 'TASK_LIST_LOADING_FAILURE',
  TASK_NAME = 'TASK_NAME',
  TASK_NOT_EXIST = 'TASK_NOT_EXIST',
  TASK_NO_PROCESS_DEFINITION = 'TASK_NO_PROCESS_DEFINITION',
  TASK_SAVE_ERROR = 'TASK_SAVE_ERROR',
  TASK_UPDATE_ERROR = 'TASK_UPDATE_ERROR',
  TASK_UPDATE_SUCESS = 'TASK_UPDATE_SUCESS',
  TASK_VARIABLE = 'TASK_VARIABLE',
  TASK_VARIABLES = 'TASK_VARIABLES',
  TENANT_ID = 'TENANT_ID',
  TOGGLE = 'TOGGLE',
  TOGGLE_NAVIGATION = 'TOGGLE_NAVIGATION',
  TYPE = 'TYPE',
  UNCLAIM_ERROR = 'UNCLAIM_ERROR',
  UNCLAIM_OK = 'UNCLAIM_OK',
  UNCLAIM_TASK = 'UNCLAIM_TASK',
  UNDEFINED_VARIABLE = 'UNDEFINED_VARIABLE',
  USE_ADD_GROUP = 'USE_ADD_GROUP',
  USE_GENERIC_FORM = 'USE_GENERIC_FORM',
  UPDATE = 'Update',
  VALUE = 'VALUE',
  VARIABLE_NAME = 'VARIABLE_NAME',
  VARIABLE_OBJECT_TYPE_NAME = 'VARIABLE_OBJECT_TYPE_NAME',
  VARIABLE_SERIALIZATION_DATA_FORMAT = 'VARIABLE_SERIALIZATION_DATA_FORMAT',
  VARIABLE_TYPE = 'VARIABLE_TYPE',
  VARIABLE_VALUE = 'VARIABLE_VALUE',
  VARIABLE_VALUE_INFO = 'VARIABLE_VALUE_INFO',
  WITHOUT_DUE_DATE = 'WITHOUT_DUE_DATE',
  WITHOUT_TENANT_ID = 'WITHOUT_TENANT_ID',
  DELEGATION = 'delegation',
  PARENT_TASK = 'parentTask',
  SEARCH_LESS_THAN = 'SEARCH_LESS_THAN',
  SEARCH_LESS_THAN_EQUALS = 'SEARCH_LESS_THAN_EQUALS',
  SEARCH_GREATER_THAN = 'SEARCH_GREATER_THAN',
  SEARCH_GREATER_THAN_EQUALS = 'SEARCH_GREATER_THAN_EQUALS',
  RESOLVED = 'RESOLVED',
  COMPLETED = 'COMPLETED',
  Completed = 'Completed',
  Updated = 'Updated',
  followUpDate = 'followUpDate',
  assignee = 'assignee',
  candidate = 'candidate',
  name = 'name',
  delegation = 'delegation',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  Resolve = 'Resolve',
  Created = 'Created',
  UpdateComment = 'UpdateComment',
  DeleteComment = 'DeleteComment',
  add = 'add',
  delete = 'delete',
  PENDING = 'PENDING'
}

export const StatusTarefaDescriptions: Record<StatusTarefa, string> = {
  [StatusTarefa.PENDING]: 'Pendente',
  [StatusTarefa.delete]: 'Removeu',
  [StatusTarefa.add]: 'Adicionou',
  [StatusTarefa.DeleteComment]: 'Removido comentário',
  [StatusTarefa.UpdateComment]: 'Atualizado comentário',
  [StatusTarefa.Created]: 'Criada',
  [StatusTarefa.Assign]: 'Atribuição',
  [StatusTarefa.AddGroupLink]: 'Adicionou ao grupo',
  [StatusTarefa.Create]: 'Criada',
  [StatusTarefa.Updated]: 'Atualizada',
  [StatusTarefa.followUpDate]: 'Data de acompanhamento',
  [StatusTarefa.assignee]: 'Responsável',
  [StatusTarefa.candidate]: 'Candidato',
  [StatusTarefa.name]: 'Nome',
  [StatusTarefa.RESOLVED]: 'Resolvida',
  [StatusTarefa.delegation]: 'Delegação de tarefa',
  [StatusTarefa.AddAttachment]: 'Anexado arquivo',
  [StatusTarefa.COMPLETED]: 'CONCLUÍDA',
  [StatusTarefa.ACTIVE]: 'ATIVO',
  [StatusTarefa.SUSPENDED]: 'SUSPENSA',
  [StatusTarefa.Completed]: 'Concluída',
  [StatusTarefa.ABORT]: 'Abortar',
  [StatusTarefa.ACTION]: 'Ação',
  [StatusTarefa.ADD]: 'Adicionar',
  [StatusTarefa.ADD_FILTER_HINT]: 'Adicionar um filtro simples',
  [StatusTarefa.ADD_GROUPS]: 'Adicionar grupos',
  [StatusTarefa.ADD_GROUP_FAILED]: 'Adicionar o grupo à tarefa selecionada falhou. Tente atualizar a página para tentar novamente.',
  [StatusTarefa.ADD_PERMISSION]: 'Adicionar permissão',
  [StatusTarefa.ADD_SORT_BY]: 'Adicionar ordenação',
  [StatusTarefa.ADD_VARIABLE]: 'Adicionar uma variável',
  [StatusTarefa.ADMIN_APP]: 'Administração',
  [StatusTarefa.AFTER]: 'depois',
  [StatusTarefa.ALL_TASKS]: 'Todas as tarefas',
  [StatusTarefa.APP_VENDOR]: 'Camunda',
  [StatusTarefa.ASC]: 'Ascendente',
  [StatusTarefa.ASSIGNED_ERROR]: 'Ocorreu um erro ao atribuir a tarefa.',
  [StatusTarefa.ASSIGNED_OK]: 'A tarefa foi atribuída.',
  [StatusTarefa.ASSIGNED_TO_YOU]: 'Atribuída a você',
  [StatusTarefa.ASSIGNEE]: 'Responsável',
  [StatusTarefa.ASSIGNEE_RESET_ERROR]: 'Não foi possível redefinir o responsável.',
  [StatusTarefa.ASSIGNEE_RESET_OK]: 'O responsável foi redefinido.',
  [StatusTarefa.ASSIGN_NOTE_CASE]: 'Você está atribuído às seguintes tarefas no mesmo caso',
  [StatusTarefa.ASSIGN_NOTE_PROCESS]: 'Você está atribuído às seguintes tarefas no mesmo processo',
  [StatusTarefa.AUTH_AUTHENTICATION_FAILED]: 'Falha na autenticação. Sua sessão pode ter expirado, faça login novamente.',
  [StatusTarefa.AUTH_DAY_CONTEXT_AFTERNOON]: 'tarde',
  [StatusTarefa.AUTH_DAY_CONTEXT_DAY]: 'dia',
  [StatusTarefa.AUTH_DAY_CONTEXT_EVENING]: 'noite',
  [StatusTarefa.AUTH_DAY_CONTEXT_MORNING]: 'manhã',
  [StatusTarefa.AUTH_DAY_CONTEXT_NIGHT]: 'madrugada',
  [StatusTarefa.AUTH_DAY_CONTEXT_WEEKEND]: 'final de semana',
  [StatusTarefa.AUTH_FAILED_TO_DISPLAY_RESOURCE]: 'Falha ao exibir recurso',
  [StatusTarefa.AUTH_LOGOUT_SUCCESSFUL]: 'Logout realizado com sucesso',
  [StatusTarefa.AUTH_LOGOUT_THANKS]: 'Obrigado por usar o Camunda hoje. Tenha um ótimo {{dayContext}}!',
  [StatusTarefa.Activate]: 'Ativar',
  [StatusTarefa.BACK]: 'Voltar',
  [StatusTarefa.BANNER_CE_EOL_TEXT]: 'É hora de migrar para o Camunda 8. O último lançamento do Camunda 7 CE será em outubro de 2025. Veja nosso <a href="https://docs.camunda.io/docs/guides/migrating-from-camunda-7/">guia de migração</a>.',
  [StatusTarefa.BEFORE]: 'antes',
  [StatusTarefa.BOOLEAN]: 'Booleano',
  [StatusTarefa.BUSINESS_KEY]: 'Chave de negócio',
  [StatusTarefa.CANCEL]: 'Cancelar',
  [StatusTarefa.CANDIDATE_GROUP]: 'Grupo candidato',
  [StatusTarefa.CANDIDATE_USER]: 'Usuário candidato',
  [StatusTarefa.CAM_WIDGET_BPMN_VIEWER_ERROR]: 'Não foi possível renderizar o diagrama:',
  [StatusTarefa.CAM_WIDGET_BPMN_VIEWER_LOADING]: 'Carregando diagrama',
  [StatusTarefa.CAM_WIDGET_CMMN_VIEWER_ERROR]: 'Não foi possível renderizar o diagrama:',
  [StatusTarefa.CAM_WIDGET_CMMN_VIEWER_LOADING]: 'Carregando diagrama',
  [StatusTarefa.CAM_WIDGET_COPY]: "Clique para copiar '{{value}}'",
  [StatusTarefa.CAM_WIDGET_COPY_LINK]: 'copiar link para a localização atual',
  [StatusTarefa.CAM_WIDGET_DMN_VIEWER_ERROR]: 'Não foi possível renderizar a tabela:',
  [StatusTarefa.CAM_WIDGET_DMN_VIEWER_LOADING]: 'Carregando tabela',
  [StatusTarefa.CAM_WIDGET_FOOTER_POWERED_BY]: 'Desenvolvido por',
  [StatusTarefa.CAM_WIDGET_FOOTER_TIMEZONE]: 'Data e hora exibidas no fuso horário local:',
  [StatusTarefa.CAM_WIDGET_HEADER_MY_PROFILE]: 'Meu perfil',
  [StatusTarefa.CAM_WIDGET_HEADER_SIGN_OUT]: 'Sair',
  [StatusTarefa.CAM_WIDGET_HEADER_SMALL_SCREEN_WARNING]: 'Esta aplicação foi concebida para telas maiores.',
  [StatusTarefa.CAM_WIDGET_HEADER_TOGGLE_NAVIGATION]: 'Alternar navegação',
  [StatusTarefa.CAM_WIDGET_INLINE_FIELD_CRIT_VALUE]: 'Valor do critério',
  [StatusTarefa.CAM_WIDGET_INLINE_FIELD_CRIT_VALUE_BTN_CHANGE]: 'Alterar',
  [StatusTarefa.CAM_WIDGET_INLINE_FIELD_CRIT_VALUE_BTN_CLOSE]: 'Fechar',
  [StatusTarefa.CAM_WIDGET_INLINE_FIELD_CRIT_VALUE_CHANGE]: 'Altere o valor do critério:',
  [StatusTarefa.CAM_WIDGET_SEARCH_MATCH_TYPE]: 'dos critérios são atendidos.',
  [StatusTarefa.CAM_WIDGET_SEARCH_MATCH_TYPE_ALL]: 'todos',
  [StatusTarefa.CAM_WIDGET_SEARCH_MATCH_TYPE_ANY]: 'qualquer',
  [StatusTarefa.CAM_WIDGET_SEARCH_TOTAL_NUMBER_RESULTS]: 'Número total de resultados',
  [StatusTarefa.CAM_WIDGET_SEARCH_VARIABLE_CASE_ATTRIBUTE]: 'Para Variáveis, ignore maiúsculas/minúsculas de ',
  [StatusTarefa.CAM_WIDGET_SEARCH_VARIABLE_CASE_NAME]: 'nome',
  [StatusTarefa.CAM_WIDGET_SEARCH_VARIABLE_CASE_VALUE]: 'valor',
  [StatusTarefa.CAM_WIDGET_STRING_DIALOG_LABEL_CLOSE]: 'Fechar',
  [StatusTarefa.CAM_WIDGET_STRING_DIALOG_LABEL_VALUE]: 'Valor',
  [StatusTarefa.CAM_WIDGET_STRING_DIALOG_TITLE]: 'Inspecionar variável "{{ name }}"',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_ABORT]: 'Abortar',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_DELETE]: 'Excluir',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_DELETE_VARIABLE]: 'Excluir a variável',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_DIALOGUE]: "Tem certeza de que deseja excluir '{{name}}'?",
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_EDIT_VARIABLE]: 'Editar a variável',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_NAME]: 'Nome',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_NULL]: '<nulo>',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_PLACEHOLDER_VALUE]: 'Valor da variável',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_REVERT_VARIABLE]: 'Reverter a variável',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_SAVE_VARIABLE]: 'Salvar a variável',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_TOOLTIP_DEFAULT_VALUE]: 'Redefinir para o valor anterior ou padrão',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_TOOLTIP_SET_NULL]: 'Definir valor como "nulo"',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_TOOLTIP_UPLOAD]: 'Enviar um novo arquivo',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_TYPE]: 'Tipo',
  [StatusTarefa.CAM_WIDGET_VARIABLES_TABLE_VALUE]: 'Valor',
  [StatusTarefa.CAM_WIDGET_VARIABLE_DIALOG_BTN_CHANGE]: 'Alterar',
  [StatusTarefa.CAM_WIDGET_VARIABLE_DIALOG_BTN_CLOSE]: 'Fechar',
  [StatusTarefa.CAM_WIDGET_VARIABLE_DIALOG_INSPECT]: 'Inspecionar variável {{ name }}',
  [StatusTarefa.CAM_WIDGET_VARIABLE_DIALOG_LABEL_OBJECT_TYPE]: 'Nome do tipo de objeto:',
  [StatusTarefa.CAM_WIDGET_VARIABLE_DIALOG_LABEL_SERIALIZATION]: 'Formato de serialização:',
  [StatusTarefa.CAM_WIDGET_VARIABLE_DIALOG_LABEL_SERIALIZED_VALUE]: 'Valor serializado',
  [StatusTarefa.CAM_WIDGET_VARIABLE_NULL]: '<nulo>',
  [StatusTarefa.CAM_WIDGET_VARIABLE_RESET]: 'Redefinir para o valor anterior ou padrão',
  [StatusTarefa.CAM_WIDGET_VARIABLE_SET_VALUE_NULL]: 'Definir valor como "nulo"',
  [StatusTarefa.CAM_WIDGET_VARIABLE_UNDEFINED]: '<indefinido>',
  [StatusTarefa.CAM_WIDGET_VARIABLE_VALUE]: 'Valor da variável',
  [StatusTarefa.CASE_DEFINITION_ID]: 'ID da definição de caso',
  [StatusTarefa.CASE_DEFINITION_KEY]: 'Chave da definição de caso',
  [StatusTarefa.CASE_DEFINITION_NAME]: 'Nome da definição de caso',
  [StatusTarefa.CASE_EXECUTION_ID]: 'ID da execução do caso',
  [StatusTarefa.CASE_EXECUTION_VARIABLE]: 'Variável de execução do caso',
  [StatusTarefa.CASE_INSTANCE_BUSINESS_KEY]: 'Chave de negócio da instância do caso',
  [StatusTarefa.CASE_INSTANCE_ID]: 'ID da instância do caso',
  [StatusTarefa.CASE_INSTANCE_VARIABLE]: 'Variável da instância do caso',
  [StatusTarefa.CASE_VARIABLE]: 'Variável do caso',
  [StatusTarefa.CHANGE]: 'Alterar',
  [StatusTarefa.CLAIM_ERROR]: 'Ocorreu um erro ao reivindicar a tarefa.',
  [StatusTarefa.CLAIM_OK]: 'A tarefa foi reivindicada.',
  [StatusTarefa.CLAIM_TASK]: 'Reivindicou',
  [StatusTarefa.CLICK_PROCESS_TO_START]: 'Clique no processo para iniciar.',
  [StatusTarefa.CLOSE]: 'Fechar',
  [StatusTarefa.CLOSE_TASK]: 'Fechar tarefa',
  [StatusTarefa.COCKPIT_APP]: 'Cockpit',
  [StatusTarefa.COMMENT]: 'Comentário',
  [StatusTarefa.COMMENT_CREATE]: 'Adicionar comentário',
  [StatusTarefa.COMMENT_MESSAGE_PLACEHOLDER]: 'Digite o comentário',
  [StatusTarefa.COMMENT_SAVE_ERROR]: 'Não foi possível salvar o comentário',
  [StatusTarefa.COMPLETE]: 'Concluir',
  [StatusTarefa.COMPLETE_ERROR]: 'Ocorreu um erro ao enviar o formulário da tarefa',
  [StatusTarefa.COMPLETE_OK]: 'A tarefa foi concluída.',
  [StatusTarefa.CREATE_TASK]: 'Criar tarefa',
  [StatusTarefa.CREATION]: 'Criado',
  [StatusTarefa.CREATION_DATE]: 'Criado',
  [StatusTarefa.CURRENT_GROUPS]: 'Grupo(s) atual(is)',
  [StatusTarefa.Claim]: 'Reivindicou',
  [StatusTarefa.Comment]: 'Comentário',
  [StatusTarefa.Complete]: 'Concluir',
  [StatusTarefa.DATE]: 'Data',
  [StatusTarefa.DELEGATE_ERROR]: 'Ocorreu um erro ao delegar a tarefa.',
  [StatusTarefa.DELEGATE_OK]: 'A tarefa foi delegada.',
  [StatusTarefa.DELEGATE_TASK]: 'Delegar',
  [StatusTarefa.DELEGATION_STATE]: 'Estado da delegação',
  [StatusTarefa.DELETE]: 'Excluir',
  [StatusTarefa.DELETE_SEARCH]: 'Remover pesquisa',
  [StatusTarefa.DESC]: 'Descendente',
  [StatusTarefa.DESCRIPTION]: 'Descrição',
  [StatusTarefa.DESERIALIZATION_ERROR]: 'Erro de desserialização',
  [StatusTarefa.DESERIALIZED]: 'Desserializado',
  [StatusTarefa.DIAGRAM]: 'Diagrama',
  [StatusTarefa.DIAGRAM_RENDER_FAILURE]: 'Falha',
  [StatusTarefa.DIRECTIVE_ENGINE_SELECT_MESSAGE_NOT_FOUND]: 'O mecanismo de processo que você está tentando acessar não existe',
  [StatusTarefa.DIRECTIVE_ENGINE_SELECT_STATUS_NOT_FOUND]: 'Não encontrado',
  [StatusTarefa.DIRECTIVE_ENGINE_SELECT_TOOLTIP]: 'Se você tiver vários mecanismos em execução, pode selecionar o mecanismo de processo aqui. Os dados exibidos nesta aplicação são baseados apenas no mecanismo selecionado.',
  [StatusTarefa.DIRECTIVE_INPLACE_TEXTFIELD_ERROR_MSG]: 'Você deve especificar uma propriedade do contexto para ser editável',
  [StatusTarefa.DOUBLE]: 'Duplo',
  [StatusTarefa.DUE]: 'Vencimento',
  [StatusTarefa.DUE_DATE]: 'Data de vencimento',
  [StatusTarefa.DUPLICATE_GROUP]: 'A tarefa já está neste grupo.',
  [StatusTarefa.Delegate]: 'Delegou',
  [StatusTarefa.Delete]: 'Excluiu',
  [StatusTarefa.DeleteAttachment]: 'Excluiu anexo',
  [StatusTarefa.DeleteGroupLink]: 'Excluiu link de grupo',
  [StatusTarefa.DeleteUserLink]: 'Excluiu link de usuário',
  [StatusTarefa.EMPTY_CONTEXT_PATH]: 'O caminho do contexto está vazio ou não definido.',
  [StatusTarefa.EMPTY_VALUE]: '<Vazio>',
  [StatusTarefa.EXECUTION_ID]: 'ID da execução',
  [StatusTarefa.EXECUTION_VARIABLE]: 'Variável de execução',
  [StatusTarefa.EXTERNAL_FORM_LINK]: 'Abrir formulário externo',
  [StatusTarefa.FAILED]: 'Falhou',
  [StatusTarefa.FAILURE]: 'Falha',
  [StatusTarefa.FILTER]: 'Filtro',
  [StatusTarefa.FILTERS]: 'Filtros',
  [StatusTarefa.FILTERS_LOADING_FAILURE]: 'Falha ao carregar os filtros. Tente atualizar a página para tentar novamente.',
  [StatusTarefa.FILTER_ADD_CRITERION]: 'Adicionou critério',
  [StatusTarefa.FILTER_ADD_VARIABLE]: 'Adicionou variável',
  [StatusTarefa.FILTER_COLOR_LABEL]: 'Cor',
  [StatusTarefa.FILTER_CREATE]: 'Criar filtro',
  [StatusTarefa.FILTER_CRITERIA_INCLUDE_ASSIGNED_TASKS]: 'Incluir tarefas atribuídas',
  [StatusTarefa.FILTER_CRITERIA_INCLUDE_ASSIGNED_TASKS_HINT]: 'Também inclui tarefas atribuídas a usuários em consultas de candidatos.<br/>O padrão é incluir apenas tarefas não atribuídas a nenhum usuário se você consultar por usuário ou grupo candidato(s).',
  [StatusTarefa.FILTER_CRITERIA_KEY]: 'Chave',
  [StatusTarefa.FILTER_CRITERIA_OPERATOR]: 'Operador',
  [StatusTarefa.FILTER_CRITERIA_VALUE]: 'Valor',
  [StatusTarefa.FILTER_CRITERION_SUPPORT_EXPRESSION]: 'Você pode utilizar expressão com este critério.',
  [StatusTarefa.FILTER_DELETE]: 'Excluir filtro',
  [StatusTarefa.FILTER_DELETION_ERROR]: 'Algo deu errado ao excluir o filtro',
  [StatusTarefa.FILTER_DELETION_SUCCESS]: 'O filtro foi excluído',
  [StatusTarefa.FILTER_DELETION_WARNING]: 'Excluir o filtro não pode ser desfeito, tem certeza que deseja continuar?',
  [StatusTarefa.FILTER_DESCRIPTION_LABEL]: 'Descrição',
  [StatusTarefa.FILTER_DESCRIPTION_PLACEHOLDER]: 'Mostra as tarefas atribuídas a mim',
  [StatusTarefa.FILTER_DETAILS]: 'Detalhes do filtro',
  [StatusTarefa.FILTER_EDIT]: 'Editar filtro',
  [StatusTarefa.FILTER_FORM_BASICS]: 'Geral',
  [StatusTarefa.FILTER_FORM_BASICS_HINT]: 'Personalize a aparência do filtro.',
  [StatusTarefa.FILTER_FORM_CRITERIA]: 'Critérios',
  [StatusTarefa.FILTER_FORM_CRITERIA_HINT]: 'Esta seção serve para definir os parâmetros usados para filtrar as tarefas. Chaves marcadas com * aceitam expressões como valor.',
  [StatusTarefa.FILTER_FORM_PERMISSIONS]: 'Permissões',
  [StatusTarefa.FILTER_FORM_PERMISSIONS_DUPLICATE_GROUP]: 'O grupo informado já possui permissões de leitura',
  [StatusTarefa.FILTER_FORM_PERMISSIONS_DUPLICATE_USER]: 'O usuário informado já possui permissões de leitura',
  [StatusTarefa.FILTER_FORM_PERMISSIONS_EDIT_HINT]: 'Para editar as permissões de leitura, você precisa de autorização para criar ou editar um filtro e uma autorização adicional para criar ou editar autorizações.',
  [StatusTarefa.FILTER_FORM_PERMISSIONS_GLOBAL]: 'Acessível por todos os usuários',
  [StatusTarefa.FILTER_FORM_PERMISSIONS_GROUP_ID]: 'ID do grupo',
  [StatusTarefa.FILTER_FORM_PERMISSIONS_HINT]: 'Esta seção serve para definir permissões de leitura para o filtro.',
  [StatusTarefa.FILTER_FORM_PERMISSIONS_IDENTITY_TYPE_GROUP]: 'grupo',
  [StatusTarefa.FILTER_FORM_PERMISSIONS_IDENTITY_TYPE_TOOLTIP]: 'Permissão aplicada a',
  [StatusTarefa.FILTER_FORM_PERMISSIONS_IDENTITY_TYPE_USER]: 'usuário',
  [StatusTarefa.FILTER_FORM_PERMISSIONS_LOADING_FAILURE]: 'Falha ao carregar as permissões. Tente atualizar a página para tentar novamente.',
  [StatusTarefa.FILTER_FORM_PERMISSIONS_REMOVE]: 'Remover',
  [StatusTarefa.FILTER_FORM_PERMISSIONS_USER_ID]: 'ID do usuário',
  [StatusTarefa.FILTER_FORM_PERMISSION_GROUP_USER]: 'Grupo / Usuário',
  [StatusTarefa.FILTER_FORM_PERMISSION_IDENTIFIER]: 'Identificador',
  [StatusTarefa.FILTER_FORM_VARIABLES]: 'Variáveis',
  [StatusTarefa.FILTER_FORM_VARIABLES_HINT]: 'Você pode definir variáveis exibidas na lista de tarefas.',
  [StatusTarefa.FILTER_FORM_VARIABLES_SHOW_UNDEFINED]: 'Mostrar variáveis indefinidas',
  [StatusTarefa.FILTER_NAME_LABEL]: 'Nome',
  [StatusTarefa.FILTER_NAME_PLACEHOLDER]: 'Minhas tarefas',
  [StatusTarefa.FILTER_NOT_FOUND]: 'Filtro não encontrado',
  [StatusTarefa.FILTER_PRIORITY_LABEL]: 'Prioridade',
  [StatusTarefa.FILTER_REFRESH_LABEL]: 'Atualização automática',
  [StatusTarefa.FILTER_REFRESH_TOOLTIP]: 'Busca automaticamente as últimas alterações e mantém a lista de tarefas atualizada',
  [StatusTarefa.FILTER_REMOVE_CRITERION]: 'Remover',
  [StatusTarefa.FILTER_REMOVE_VARIABLE]: 'Remover',
  [StatusTarefa.FILTER_SAVE_ERROR]: 'Algo deu errado ao salvar o filtro',
  [StatusTarefa.FILTER_SAVE_SUCCESS]: 'O filtro foi salvo',
  [StatusTarefa.FILTER_VARIABLES_AMOUNT_WARNING]: 'Exibir muitas variáveis na lista de tarefas pode impactar a experiência do usuário.',
  [StatusTarefa.FILTER_VARIABLE_LABEL]: 'Rótulo',
  [StatusTarefa.FILTER_VARIABLE_LABEL_PLACEHOLDER]: 'Rótulo legível',
  [StatusTarefa.FILTER_VARIABLE_NAME]: 'Nome',
  [StatusTarefa.FILTER_VARIABLE_NAME_PLACEHOLDER]: 'Nome da variável',
  [StatusTarefa.FINISHED]: 'Finalizado',
  [StatusTarefa.FIRST_LOGIN_HEADING]: 'Bem-vindo ao Camunda',
  [StatusTarefa.FIRST_LOGIN_INFO]: 'Parece que esta é sua primeira vez usando os webapps. Confira a <a href="/camunda-welcome">Página de Boas-vindas do Camunda</a> para uma visão geral rápida.',
  [StatusTarefa.FOLLOW_UP]: 'Acompanhamento',
  [StatusTarefa.FOLLOW_UP_DATE]: 'Data de acompanhamento',
  [StatusTarefa.FORM]: 'Formulário',
  [StatusTarefa.FORM_FAILURE]: 'Falha no formulário:',
  [StatusTarefa.GROUP]: 'Grupo',
  [StatusTarefa.GROUPS]: 'Grupos',
  [StatusTarefa.GROUPS_ADD]: 'Adicionar grupos',
  [StatusTarefa.GROUP_ADD]: 'Adicionar um grupo',
  [StatusTarefa.GROUP_ADD_ERROR]: 'Não foi possível adicionar o grupo',
  [StatusTarefa.GROUP_DELETE_ERROR]: 'Não foi possível remover o grupo',
  [StatusTarefa.GROUP_ID]: 'ID do grupo',
  [StatusTarefa.GROUP_REMOVE]: 'Remover grupo',
  [StatusTarefa.HISTORY]: 'Histórico',
  [StatusTarefa.INIT_EXTERNAL_FORM_FAILED]: 'Não é possível inicializar a URL do formulário externo: o ID da tarefa ou a chave da definição do processo devem ser fornecidos. Tente atualizar a página para tentar novamente.',
  [StatusTarefa.INIT_GROUPS_FAILURE]: 'Falha ao carregar os grupos da tarefa selecionada. Tente atualizar a página para tentar novamente.',
  [StatusTarefa.INSTANCE_LINK]: 'Link para visualização da instância.',
  [StatusTarefa.INSTANCE_SUSPENDED]: 'A tarefa está atualmente suspensa',
  [StatusTarefa.INTEGER]: 'Inteiro',
  [StatusTarefa.INVALID_DATE]: "Data inválida: o padrão deve ser 'yyyy-MM-ddTHH:mm:ss'",
  [StatusTarefa.INVALID_DATE_VALUE]: 'Data inválida: o valor da data é inválido',
  [StatusTarefa.INVALID_SEARCH]: 'Esta consulta de pesquisa não é válida',
  [StatusTarefa.INVOLVED_USER]: 'Usuário envolvido',
  [StatusTarefa.LIKE]: 'curtir',
  [StatusTarefa.LOADING]: 'Carregando…',
  [StatusTarefa.LOAD_VARIABLES]: 'Carregar variáveis',
  [StatusTarefa.LOAD_VARIABLES_FAILURE]: 'Não foi possível carregar as variáveis',
  [StatusTarefa.LONG]: 'Longo',
  [StatusTarefa.MANAGE_ACCOUNT]: 'Gerenciar sua conta',
  [StatusTarefa.MANAGE_GROUPS]: 'Gerenciar grupos',
  [StatusTarefa.MATCH_TYPE]: 'dos critérios são atendidos.',
  [StatusTarefa.MATCH_TYPE_ALL]: 'todos',
  [StatusTarefa.MATCH_TYPE_ANY]: 'qualquer',
  [StatusTarefa.MY_PROFILE]: 'Meu perfil',
  [StatusTarefa.NAME]: 'Nome',
  [StatusTarefa.NEW_TASK_ASSIGNEE]: 'Responsável',
  [StatusTarefa.NEW_TASK_DESCRIPTION]: 'Descrição',
  [StatusTarefa.NEW_TASK_NAME]: 'Nome',
  [StatusTarefa.NEW_TASK_TENANT_ID]: 'ID do locatário',
  [StatusTarefa.NONE]: 'Nenhum',
  [StatusTarefa.NO_AVAILABLE_FILTER]: 'Nenhum filtro disponível.',
  [StatusTarefa.NO_DESCRIPTION]: 'Não há descrição da tarefa.',
  [StatusTarefa.NO_DIAGRAM]: 'Não há diagrama disponível.',
  [StatusTarefa.NO_HISTORY]: 'Não há histórico para a tarefa.',
  [StatusTarefa.NO_MATCHING_TASK]: 'Nenhuma tarefa encontrada para os filtros.',
  [StatusTarefa.NO_PROCESS_DEFINITION_AVAILABLE]: 'Não há definições de processo disponíveis.',
  [StatusTarefa.NO_TASK_FORM]: '',
  [StatusTarefa.NO_TASK_VARIABLES]: 'A tarefa não contém variáveis',
  [StatusTarefa.OPERATOR]: 'Operador',
  [StatusTarefa.OWNER]: 'Proprietário',
  [StatusTarefa.FILTER_FORM_PERMISSIONS_SAVE_ERROR]: 'Algo deu errado ao salvar as permissões',
  [StatusTarefa.OWNER_IS_YOU]: 'Você é o proprietário',
  [StatusTarefa.PAGES_MSG_ACCESS_DENIED]: 'Você não tem autorização para {{missingAuths}}.',
  [StatusTarefa.PAGES_MSG_ACCESS_DENIED_RESOURCE_ID]: 'Você não tem autorização para {{permissionName}} {{resourceName}} {{resourceId}}.',
  [StatusTarefa.PAGES_MSG_ACTION_DENIED]: 'A execução de uma ação foi negada pelo servidor. Tente atualizar a página.',
  [StatusTarefa.PAGES_MSG_COMMUNICATION_ERROR]: 'O aplicativo recebeu uma resposta inesperada {{status}} do servidor. Tente atualizar a página ou faça login novamente.',
  [StatusTarefa.PAGES_MSG_ENGINE_NOT_EXISTS]: 'O mecanismo de processo que você está tentando acessar não existe.',
  [StatusTarefa.PAGES_MSG_NOT_FOUND]: 'O recurso solicitado não foi encontrado.',
  [StatusTarefa.PAGES_MSG_REQUEST_TIMEOUT]: 'Sua solicitação expirou. Tente atualizar a página.',
  [StatusTarefa.PAGES_MSG_SERVER_ERROR]: 'O servidor relatou um erro interno. Tente atualizar a página ou faça login novamente.',
  [StatusTarefa.PAGES_STATUS_ACCESS_DENIED]: 'Acesso negado',
  [StatusTarefa.PAGES_STATUS_COMMUNICATION_ERROR]: 'Erro de comunicação',
  [StatusTarefa.PAGES_STATUS_NOT_FOUND]: 'Não encontrado',
  [StatusTarefa.PAGES_STATUS_REQUEST_TIMEOUT]: 'Tempo de solicitação esgotado',
  [StatusTarefa.PAGES_STATUS_SERVER_ERROR]: 'Erro do servidor',
  [StatusTarefa.PAGE_LOGIN_ERROR_MSG]: 'Credenciais incorretas, usuário bloqueado ou sem permissão de acesso ao aplicativo',
  [StatusTarefa.PAGE_LOGIN_FAILED]: 'Falha no login',
  [StatusTarefa.PAGE_LOGIN_PASSWORD]: 'Senha',
  [StatusTarefa.PAGE_LOGIN_PLEASE_SIGN_IN]: 'Por favor, faça login',
  [StatusTarefa.PAGE_LOGIN_SIGN_IN_ACTION]: 'Entrar',
  [StatusTarefa.PAGE_LOGIN_USERNAME]: 'Usuário',
  [StatusTarefa.PAGINATION_FIRST]: 'Primeiro',
  [StatusTarefa.PAGINATION_LAST]: 'Último',
  [StatusTarefa.PAGINATION_NEXT]: 'Próximo',
  [StatusTarefa.PAGINATION_PREVIOUS]: 'Anterior',
  [StatusTarefa.PRIORITY]: 'Prioridade',
  [StatusTarefa.PROCESS_DEFINITION]: 'Definição de Processo',
  [StatusTarefa.PROCESS_DEFINITION_ID]: 'ID da Definição de Processo',
  [StatusTarefa.PROCESS_DEFINITION_KEY]: 'Chave da Definição de Processo',
  [StatusTarefa.PROCESS_DEFINITION_NAME]: 'Nome da Definição de Processo',
  [StatusTarefa.PROCESS_EXTERNAL_FORM_NOTE]: 'Este processo contém um formulário externo para iniciar uma nova instância. Para abrir o formulário externo, clique no link "Abrir formulário externo" abaixo.',
  [StatusTarefa.PROCESS_INSTANCE]: 'Instância de Processo',
  [StatusTarefa.PROCESS_INSTANCE_BUSINESS_KEY]: 'Chave de Negócio da Instância de Processo',
  [StatusTarefa.PROCESS_INSTANCE_ID]: 'ID da Instância de Processo',
  [StatusTarefa.PROCESS_NAME]: 'Nome do processo',
  [StatusTarefa.PROCESS_START_ERROR]: 'O processo não pôde ser iniciado.',
  [StatusTarefa.PROCESS_START_OK]: 'O processo foi iniciado.',
  [StatusTarefa.PROCESS_VARIABLE]: 'Variável do Processo',
  [StatusTarefa.PROPERTY]: 'Propriedade',
  [StatusTarefa.REMOVE]: 'Remover',
  [StatusTarefa.REMOVE_GROUP_FAILED]: 'A remoção do grupo da tarefa selecionada falhou. Tente atualizar a página para tentar novamente.',
  [StatusTarefa.REMOVE_SORTING]: 'Remover ordenação',
  [StatusTarefa.RENDERING]: 'Renderizando…',
  [StatusTarefa.REQUIRED_FIELD]: 'Campo obrigatório',
  [StatusTarefa.REQUIRED_HEX_COLOR_FIELD]: 'O valor deve ser uma cor hexadecimal',
  [StatusTarefa.REQUIRED_INTEGER_FIELD]: 'O valor deve ser um número inteiro',
  [StatusTarefa.REQUIRE_UNIQUE_KEY]: 'A chave deve ser única',
  [StatusTarefa.REQUIRE_UNIQUE_NAME]: 'O nome deve ser único',
  [StatusTarefa.RESET_DUE_DATE]: 'Redefinir data de vencimento',
  [StatusTarefa.RESET_FOLLOW_UP_DATE]: 'Redefinir data de acompanhamento',
  [StatusTarefa.RESET_PAGE]: 'Redefinir número da página',
  [StatusTarefa.RESET_TASK_ASSIGNEE]: 'Redefinir responsável',
  [StatusTarefa.RESOLVE_ERROR]: 'Ocorreu um erro ao resolver a tarefa.',
  [StatusTarefa.RESOLVE_OK]: 'A tarefa foi resolvida.',
  [StatusTarefa.RESTRICTION_NOTICE]: 'Os parâmetros de busca atuais não retornaram nenhuma tarefa. Tente redefinir os parâmetros de busca.',
  [StatusTarefa.Resolve]: 'Resolveu',
  [StatusTarefa.SAVE]: 'Salvar',
  [StatusTarefa.SAVE_HINT]: 'Salve o estado atual do formulário para completá-lo depois',
  [StatusTarefa.SEARCH_BY_TASK_NAME]: 'Buscar pelo nome da tarefa, sensível a maiúsculas/minúsculas.',
  [StatusTarefa.SEARCH_PLACEHOLDER]: 'Filtrar tarefas',
  [StatusTarefa.SEARCH_PROCESS_BY_NAME]: 'Buscar pelo nome do processo.',
  [StatusTarefa.SEARCH_TASK_BY_NAME]: 'Buscar pelo nome da tarefa, sensível a maiúsculas/minúsculas.',
  [StatusTarefa.SELECT_TASK_IN_LIST]: 'Selecione uma tarefa na lista.',
  [StatusTarefa.SERIALIZED]: 'Serializado',
  [StatusTarefa.SERVICES_RESOURCE_RESOLVER_AUTH_FAILED]: 'Falha na autenticação. Sua sessão pode ter expirado, faça login novamente.',
  [StatusTarefa.SERVICES_RESOURCE_RESOLVER_DISPLAY_FAILED]: 'Falha ao exibir {{resourceName}}',
  [StatusTarefa.SERVICES_RESOURCE_RESOLVER_ID_NOT_FOUND]: 'Nenhum {{resourceName}} com ID {{id}}',
  [StatusTarefa.SERVICES_RESOURCE_RESOLVER_NO_PROMISE]: 'Nenhuma promise retornada por #resolve',
  [StatusTarefa.SERVICES_RESOURCE_RESOLVER_RECEIVED_STATUS]: 'Recebido {{status}} do servidor.',
  [StatusTarefa.SET]: 'Definir',
  [StatusTarefa.SET_DUE_DATE]: 'Definir data de vencimento',
  [StatusTarefa.SET_FOLLOW_UP_DATE]: 'Definir data de acompanhamento',
  [StatusTarefa.SHORT]: 'Curto',
  [StatusTarefa.SHORTCUT]: 'Atalho',
  [StatusTarefa.SHORTCUT_HELP]: 'Atalhos de teclado',
  [StatusTarefa.SHOW_LESS]: 'Mostrar menos',
  [StatusTarefa.SHOW_MORE]: 'Mostrar mais',
  [StatusTarefa.SIGN_OUT_ACTION]: 'Sair',
  [StatusTarefa.SORT_BY]: 'Ordenar por',
  [StatusTarefa.START]: 'Iniciar',
  [StatusTarefa.START_PROCESS]: 'Iniciar processo',
  [StatusTarefa.STRING]: 'Texto',
  [StatusTarefa.SUBMIT]: 'Enviar',
  [StatusTarefa.SUCCESSFUL]: 'Bem-sucedido',
  [StatusTarefa.TASK]: 'Tarefa',
  [StatusTarefa.TASKLIST_APP]: 'Lista de Tarefas',
  [StatusTarefa.TASKS]: 'Tarefas',
  [StatusTarefa.TASK_DEFINITION_KEY]: 'Chave da Definição da Tarefa',
  [StatusTarefa.TASK_EXTERNAL_FORM_NOTE]: 'Esta tarefa contém um formulário externo para ser concluída. Para abrir o formulário externo, clique no link "Abrir formulário externo" abaixo.',
  [StatusTarefa.TASK_HAS_BEEN_REMOVED]: 'A tarefa foi removida.',
  [StatusTarefa.TASK_LIST_LOADING_FAILURE]: 'Falha ao carregar a lista de tarefas. Tente atualizar a página para tentar novamente.',
  [StatusTarefa.TASK_NAME]: 'Nome da tarefa',
  [StatusTarefa.TASK_NOT_EXIST]: 'A tarefa não existe mais',
  [StatusTarefa.TASK_NO_PROCESS_DEFINITION]: 'Não foi possível encontrar a definição do processo da tarefa.',
  [StatusTarefa.TASK_SAVE_ERROR]: 'Algo deu errado ao salvar a tarefa',
  [StatusTarefa.TASK_UPDATE_ERROR]: 'A tarefa não pôde ser salva.',
  [StatusTarefa.TASK_UPDATE_SUCESS]: 'A tarefa foi salva.',
  [StatusTarefa.TASK_VARIABLE]: 'Variável da Tarefa',
  [StatusTarefa.TASK_VARIABLES]: 'Variáveis',
  [StatusTarefa.TENANT_ID]: 'ID do locatário',
  [StatusTarefa.TOGGLE]: 'Alternar',
  [StatusTarefa.TOGGLE_NAVIGATION]: 'Alternar navegação',
  [StatusTarefa.TYPE]: 'Tipo',
  [StatusTarefa.UNCLAIM_ERROR]: 'Ocorreu um erro ao desatribuir a tarefa.',
  [StatusTarefa.UNCLAIM_OK]: 'A tarefa foi desatribuída.',
  [StatusTarefa.UNCLAIM_TASK]: 'Desatribuir',
  [StatusTarefa.UNDEFINED_VARIABLE]: '<Indefinido>',
  [StatusTarefa.USE_ADD_GROUP]: 'Você pode adicionar um grupo digitando o ID do grupo no campo e depois clicando no botão de mais.',
  [StatusTarefa.USE_GENERIC_FORM]: 'Você pode definir variáveis usando um formulário genérico, clicando no link "Adicionar uma variável" abaixo.',
  [StatusTarefa.VALUE]: 'Valor',
  [StatusTarefa.VARIABLE_NAME]: 'Nome da variável',
  [StatusTarefa.VARIABLE_OBJECT_TYPE_NAME]: 'Nome do tipo de objeto',
  [StatusTarefa.VARIABLE_SERIALIZATION_DATA_FORMAT]: 'Formato de serialização',
  [StatusTarefa.VARIABLE_TYPE]: 'Tipo da variável',
  [StatusTarefa.VARIABLE_VALUE]: 'Valor',
  [StatusTarefa.VARIABLE_VALUE_INFO]: 'Informação do valor',
  [StatusTarefa.WITHOUT_DUE_DATE]: 'Sem data de vencimento',
  [StatusTarefa.WITHOUT_TENANT_ID]: 'Sem ID do locatário',
  [StatusTarefa.SEARCH_LESS_THAN]: '<',
  [StatusTarefa.SEARCH_LESS_THAN_EQUALS]: '<=',
  [StatusTarefa.SEARCH_GREATER_THAN]: '>',
  [StatusTarefa.SEARCH_GREATER_THAN_EQUALS]: '>=',
  [StatusTarefa.SET_OWNER]: "Alterado proprietário",
  [StatusTarefa.SET_PRIORITY]: "Alterado prioridade",
  [StatusTarefa.SUSPEND]: "Suspenso",
  [StatusTarefa.AddUserLink]: "Adicionou link de usuário",
  [StatusTarefa.PARENT_TASK]: "Tarefa pai",
  [StatusTarefa.UPDATE]: "Atualizado"
};

